export const ORIGIN_CITY_OPTIONS = [
  "Banff, AB, Canada",
  "Canmore, AB, Canada",
  "Calgary, AB, Canada",
  "Edmonton, AB, Canada",
  "Red Deer, AB, Canada",
  "Lethbridge, AB, Canada",
  "Medicine Hat, AB, Canada",
  "Vancouver, BC, Canada",
  "Victoria, BC, Canada",
  "Kelowna, BC, Canada",
  "Whistler, BC, Canada",
  "Kamloops, BC, Canada",
  "Nanaimo, BC, Canada",
  "Prince George, BC, Canada",
  "Regina, SK, Canada",
  "Saskatoon, SK, Canada",
  "Winnipeg, MB, Canada",
  "Toronto, ON, Canada",
  "Ottawa, ON, Canada",
  "Hamilton, ON, Canada",
  "London, ON, Canada",
  "Kingston, ON, Canada",
  "Waterloo, ON, Canada",
  "Montreal, QC, Canada",
  "Quebec City, QC, Canada",
  "Halifax, NS, Canada",
  "Fredericton, NB, Canada",
  "Moncton, NB, Canada",
  "Charlottetown, PE, Canada",
  "St. John's, NL, Canada",
  "Whitehorse, YT, Canada",
  "Yellowknife, NT, Canada",
  "New York, NY, USA",
  "Seattle, WA, USA",
  "Portland, OR, USA",
  "San Francisco, CA, USA",
  "Los Angeles, CA, USA",
  "Denver, CO, USA",
  "Chicago, IL, USA",
  "Boston, MA, USA",
  "London, England, UK",
  "Manchester, England, UK",
  "Bristol, England, UK",
  "Edinburgh, Scotland, UK",
  "Glasgow, Scotland, UK",
  "Dublin, Ireland",
  "Cork, Ireland",
  "Paris, France",
  "Lyon, France",
  "Berlin, Germany",
  "Munich, Germany",
  "Amsterdam, Netherlands",
  "Rotterdam, Netherlands",
  "Copenhagen, Denmark",
  "Stockholm, Sweden",
  "Oslo, Norway",
  "Zurich, Switzerland",
  "Geneva, Switzerland",
  "Madrid, Spain",
  "Barcelona, Spain",
  "Rome, Italy",
  "Milan, Italy",
  "Vienna, Austria",
  "Prague, Czechia",
  "Warsaw, Poland",
  "Budapest, Hungary",
  "Sydney, NSW, Australia",
  "Melbourne, VIC, Australia",
  "Brisbane, QLD, Australia",
  "Perth, WA, Australia",
  "Adelaide, SA, Australia",
  "Hobart, TAS, Australia",
  "Auckland, New Zealand",
  "Wellington, New Zealand",
  "Christchurch, New Zealand",
  "Queenstown, New Zealand",
  "Tokyo, Japan",
  "Osaka, Japan",
  "Kyoto, Japan",
  "Seoul, South Korea",
  "Busan, South Korea",
  "Taipei, Taiwan",
  "Singapore",
  "Hong Kong",
  "Bangkok, Thailand",
  "Chiang Mai, Thailand",
  "Ho Chi Minh City, Vietnam",
  "Hanoi, Vietnam",
  "Manila, Philippines",
  "Mumbai, India",
  "Delhi, India",
  "Mexico City, Mexico",
  "Guadalajara, Mexico",
  "Santiago, Chile",
  "Buenos Aires, Argentina",
  "Sao Paulo, Brazil",
  "Rio de Janeiro, Brazil",
  "Bogota, Colombia",
  "Lima, Peru",
  "Cape Town, South Africa",
  "Johannesburg, South Africa",
].sort((a, b) => a.localeCompare(b));
