export const STARTER_EVENT_SOURCES = [
  {
    name: "Banff Centre Events",
    url: "https://www.banffcentre.ca/events",
    town: "Banff",
    sourceType: "html",
    enabled: true,
    trusted: true,
  },
  {
    name: "Banff & Lake Louise Tourism Events",
    url: "https://www.banfflakelouise.com/events",
    town: "Banff",
    sourceType: "html",
    enabled: true,
    trusted: true,
  },
  {
    name: "Rose & Crown Banff Events",
    url: "https://roseandcrown.ca/events/",
    town: "Banff",
    sourceType: "html",
    enabled: true,
    trusted: true,
  },
  {
    name: "The Dusty Boot Banff Live Music & Specials",
    url: "https://www.dustybootbanff.com/live-music-specials",
    town: "Banff",
    sourceType: "html",
    enabled: true,
    trusted: true,
  },
  {
    name: "The Fat Ox Banff Happenings",
    url: "https://fatoxbanff.ca/happenings/",
    town: "Banff",
    sourceType: "html",
    enabled: true,
    trusted: true,
  },
  {
    name: "Lake Louise Ski Resort Events",
    url: "https://www.skilouise.com/things-to-do/category/events/",
    town: "Lake Louise",
    sourceType: "html",
    enabled: true,
    trusted: true,
  },
];
