export const STARTER_EVENT_SOURCES = [
  {
    name: "Banff Centre Events",
    url: "https://www.banffcentre.ca/events",
    town: "Banff",
    sourceType: "html",
    enabled: true,
    trusted: true,
  },
  {
    name: "Banff & Lake Louise Tourism Events",
    url: "https://www.banfflakelouise.com/events",
    town: "Banff",
    sourceType: "html",
    enabled: true,
    trusted: true,
  },
  {
    name: "Rose & Crown Banff Events",
    url: "https://roseandcrown.ca/events/",
    town: "Banff",
    sourceType: "html",
    enabled: true,
    trusted: true,
  },
  {
    name: "The Dusty Boot Banff Live Music & Specials",
    url: "https://www.dustybootbanff.com/live-music-specials",
    town: "Banff",
    sourceType: "html",
    enabled: true,
    trusted: true,
  },
  {
    name: "The Fat Ox Banff Happenings",
    url: "https://fatoxbanff.ca/happenings/",
    town: "Banff",
    sourceType: "html",
    enabled: true,
    trusted: true,
  },
  {
    name: "THE BOSS Kitchen & Bar Happy Hour",
    url: "https://thebossbanff.com/menu/",
    town: "Banff",
    sourceType: "html",
    enabled: true,
    trusted: true,
  },
  {
    name: "Banff Social Happy Hour",
    url: "https://banffsocial.ca/menus",
    town: "Banff",
    sourceType: "html",
    enabled: true,
    trusted: true,
  },
  {
    name: "Lake Louise Ski Resort Events",
    url: "https://www.skilouise.com/things-to-do/category/events/",
    town: "Lake Louise",
    sourceType: "html",
    enabled: true,
    trusted: true,
  },
  {
    name: "Fairmont Chateau Lake Louise Events Calendar",
    url: "https://www.chateau-lake-louise.com/experience/events-calendar/",
    town: "Lake Louise",
    sourceType: "html",
    enabled: true,
    trusted: true,
  },
  {
    name: "SkiBig3 Events",
    url: "https://www.skibig3.com/events/?page=1",
    town: "Banff",
    sourceType: "html",
    enabled: true,
    trusted: true,
  },
  {
    name: "Explore Canmore Events",
    url: "https://www.explorecanmore.ca/events/",
    town: "Canmore",
    sourceType: "html",
    enabled: true,
    trusted: true,
  },
  {
    name: "Carter-Ryan Theatre",
    url: "https://www.carter-ryan.com/theatre",
    town: "Canmore",
    sourceType: "html",
    enabled: true,
    trusted: true,
  },
  {
    name: "Rocky Mountain Live",
    url: "https://rockymountainlive.ca",
    town: "Banff",
    sourceType: "html",
    enabled: true,
    trusted: true,
  },
  {
    name: "Canmore Brewing Company Upcoming Events",
    url: "https://www.canmorebrewing.com/upcoming-events",
    town: "Canmore",
    sourceType: "html",
    enabled: true,
    trusted: true,
  },
];
